2024-11-06 01:42:02,274 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-06 01:42:02,274 - INFO - [33mPress CTRL+C to quit[0m
2024-11-06 01:42:36,162 - INFO - 120.126.47.13 - - [06/Nov/2024 01:42:36] "GET / HTTP/1.1" 200 -
2024-11-06 01:42:43,176 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 77, in get_treatment
    treatment = get_number(dcis, pathology)
  File "app.py", line 54, in get_number
    sheet_name = get_sheet_name(paraA, paraB)
  File "app.py", line 50, in get_sheet_name
    raise ValueError("Invalid values for paraA and paraB")
ValueError: Invalid values for paraA and paraB
2024-11-06 01:42:43,180 - INFO - 120.126.47.13 - - [06/Nov/2024 01:42:43] "[35m[1mGET /get_treatment?paraA=1098&paraB=9377 HTTP/1.1[0m" 500 -
2024-11-06 01:44:29,284 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-06 01:44:29,287 - INFO - [33mPress CTRL+C to quit[0m
2024-11-06 01:44:45,463 - ERROR - protocolid: {protocolid}
2024-11-06 01:44:45,463 - ERROR - patientid: {patientid}
2024-11-06 01:44:46,907 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 77, in get_treatment
    treatment = get_number(dcis, pathology)
  File "app.py", line 54, in get_number
    sheet_name = get_sheet_name(paraA, paraB)
  File "app.py", line 50, in get_sheet_name
    raise ValueError("Invalid values for paraA and paraB")
ValueError: Invalid values for paraA and paraB
2024-11-06 01:44:46,909 - INFO - 120.126.47.13 - - [06/Nov/2024 01:44:46] "[35m[1mGET /get_treatment?paraA=1098&paraB=9377 HTTP/1.1[0m" 500 -
2024-11-06 01:46:19,622 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-06 01:46:19,624 - INFO - [33mPress CTRL+C to quit[0m
2024-11-06 01:49:28,007 - ERROR - protocolid:1098
2024-11-06 01:49:28,007 - ERROR - patientid:9377
2024-11-06 01:49:29,438 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 77, in get_treatment
    treatment = get_number(dcis, pathology)
  File "app.py", line 54, in get_number
    sheet_name = get_sheet_name(paraA, paraB)
  File "app.py", line 50, in get_sheet_name
    raise ValueError("Invalid values for paraA and paraB")
ValueError: Invalid values for paraA and paraB
2024-11-06 01:49:29,441 - INFO - 120.126.47.13 - - [06/Nov/2024 01:49:29] "[35m[1mGET /get_treatment?paraA=1098&paraB=9377 HTTP/1.1[0m" 500 -
2024-11-06 01:50:46,428 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-06 01:50:46,428 - INFO - [33mPress CTRL+C to quit[0m
2024-11-06 01:50:50,542 - ERROR - protocolid:1098
2024-11-06 01:50:50,542 - ERROR - patientid:9377
2024-11-06 01:50:51,955 - ERROR - dcis:2
2024-11-06 01:50:51,955 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 78, in get_treatment
    logging.error("pathology:"+pathology)
TypeError: can only concatenate str (not "NoneType") to str
2024-11-06 01:50:51,958 - INFO - 120.126.47.13 - - [06/Nov/2024 01:50:51] "[35m[1mGET /get_treatment?paraA=1098&paraB=9377 HTTP/1.1[0m" 500 -
2024-11-06 01:53:51,900 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-06 01:53:51,906 - INFO - [33mPress CTRL+C to quit[0m
2024-11-06 01:53:55,038 - ERROR - protocolid:1098
2024-11-06 01:53:55,038 - ERROR - patientid:9377
2024-11-06 01:53:56,495 - ERROR - dcis:2
2024-11-06 01:53:56,495 - ERROR - pathology:2
2024-11-06 01:54:00,389 - INFO - 120.126.47.13 - - [06/Nov/2024 01:54:00] "GET /get_treatment?paraA=1098&paraB=9377 HTTP/1.1" 200 -
2024-11-06 02:10:01,868 - ERROR - 36.226.71.243 - - [06/Nov/2024 02:10:01] code 400, message Bad HTTP/0.9 request type ("\x16\x03\x01\x06à\x01\x00\x06Ü\x03\x03'")
2024-11-06 02:10:01,869 - INFO - 36.226.71.243 - - [06/Nov/2024 02:10:01] "[35m[1m\x16\x03\x01\x06à\x01\x00\x06Ü\x03\x03'\x1e´®j¥¢\x97þ\x11£[0m" HTTPStatus.BAD_REQUEST -
2024-11-06 02:10:04,151 - ERROR - 36.226.71.243 - - [06/Nov/2024 02:10:04] code 400, message Bad request version ('ÚÚ\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x06S\x8a\x8a\x00\x00\x00\x05\x00\x05\x01\x00\x00\x00\x00ÿ\x01\x00\x01\x00\x00')
2024-11-06 02:10:04,152 - INFO - 36.226.71.243 - - [06/Nov/2024 02:10:04] "[35m[1m\x16\x03\x01\x06À\x01\x00\x06¼\x03\x03Ôµ*J¥Aß>ÿS¾\x0dÛ\x87³c¯5Dµ\x17®\x135û¢?é\x1a£\x9aë Û½X\x9fÄ6\x1eþÝ!\x8cÛÅ÷¯÷g\x0b4\x96\x08Ù\x06DeËÖ¾\x1bÙû\x95\x00 ÚÚ\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x06S\x8a\x8a\x00\x00\x00\x05\x00\x05\x01\x00\x00\x00\x00ÿ\x01\x00\x01\x00\x00[0m" HTTPStatus.BAD_REQUEST -
2024-11-06 02:10:04,169 - INFO - 36.226.71.243 - - [06/Nov/2024 02:10:04] "[33mGET /get_treatment/1098/assign/9377?form_id=5606 HTTP/1.1[0m" 404 -
2024-11-06 02:10:06,521 - INFO - 36.226.71.243 - - [06/Nov/2024 02:10:06] "[33mGET /get_treatment/1098/assign/9377?form_id=5606 HTTP/1.1[0m" 404 -
2024-11-06 02:10:08,895 - INFO - 36.226.71.243 - - [06/Nov/2024 02:10:08] "[33mGET /get_treatment/1098/assign/9377?form_id=5606 HTTP/1.1[0m" 404 -
2024-11-06 02:10:08,975 - INFO - 36.226.71.243 - - [06/Nov/2024 02:10:08] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2024-11-06 02:25:22,565 - ERROR - 36.226.71.243 - - [06/Nov/2024 02:25:22] code 400, message Bad request version ('J\x00ð')
2024-11-06 02:25:22,566 - INFO - 36.226.71.243 - - [06/Nov/2024 02:25:22] "[35m[1m\x16\x03\x01\x07\x00\x01\x00\x06ü\x03\x03¤Aÿ1ì\x15±\x85Éð#_\x0dR9\x08\x1b\x7fºÊê\x00Ü:Áç¦f\x87|\x81Ø \x84¯À ÁÙ\x82\x1cj\x9aû\x82Ø\x9c%À^\x98æ³ÞOLX\x85¥ß!Ðè\x17x\x00 ÚÚ\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x06\x93ºº\x00\x00ÿ\x01\x00\x01\x00\x00-\x00\x02\x01\x01Di\x00\x05\x00\x03\x02h2þ\x0d\x01\x1a\x00\x00\x01\x00\x01ë\x00 m\x056ô\x86\x8aàO\x8a;Q\x8f\x98l£\x88»$]Ö\x1b#\x85°VN1ö;7\x1dJ\x00ð[0m" HTTPStatus.BAD_REQUEST -
2024-11-06 02:25:22,567 - INFO - 36.226.71.243 - - [06/Nov/2024 02:25:22] "[33mGET /get_treatment/1098/assign/9377?form_id=5606 HTTP/1.1[0m" 404 -
2024-11-06 02:25:22,694 - ERROR - 36.226.71.243 - - [06/Nov/2024 02:25:22] code 400, message Bad request version ('¦y\x11g¼VÀ')
2024-11-06 02:25:22,695 - INFO - 36.226.71.243 - - [06/Nov/2024 02:25:22] "[35m[1m\x16\x03\x01\x06À\x01\x00\x06¼\x03\x03D«\x94ö!L\x87¸¢\x0bâw?÷\x12ÁxÑ½õ¬µ\x9b´2\x87·_Þ¥\x9eü ÷X®¦\x85Û\x83\x9e\x94¿Áôù4\x9a!\x02ª\x03¾ùäüIòJ\x88ë¦\x08\x9e\x16\x00 êê\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x06S**\x00\x00þ\x0d\x00Ú\x00\x00\x01\x00\x01;\x00 ³[2VÙTJ\x11OÆ\x1e\x19\x0d Æ8·1«fß\x96"\x07\x19@kVòÇ°\x11\x00°@ëQ[Õ(Ë\x14\x03_Ò\x8eyßÈyE\x88kuÍ\x04\x9aþövÊ¸¼`§À\x81íúJö:\x8c\x03;5ë\x8d~\x1eÂÊ\x7fÍTõ\x05r\x03£\x83xO\x09\x91×ÐÑ\x86+ñixÊ\x15M?*°\x8bÎ\x9e÷M\x89$,\x0f[\x0f\x81TËOÂ\x185\x9bSÚZ)\x1e*¹a¢\x87p_gf\x98\x00~|boõüx\x89²\x1d\x14\x9cpj\x8a\x1c\x0c(5ß\x0e=\x00NEA·ºj@á²\x7f!"NÓK\x1e\x00³}lr:\x199Ïÿ_Ì\x95ñò\x95\x1b|DBy<êê?«;\x00\x05\x00\x05\x01\x00\x00\x00\x00\x00+\x00\x07\x06êê\x03\x04\x03\x03Di\x00\x05\x00\x03\x02h2\x00\x0b\x00\x02\x01\x00\x00#\x00\x00\x003\x04ï\x04íjj\x00\x01\x00c\x99\x04Àcã\x94ÍtdC¨v³.U\x1fß9ª¹\x81"\x9e!ÆÐ\x82±\x04wu\x1bñ\x83t üºx5Í5\x84\x8eý+\x92\x0b¦y\x11g¼VÀ[0m" HTTPStatus.BAD_REQUEST -
2024-11-06 02:37:49,326 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 70, in get_treatment
    logging.error("protocolid:"+protocolid)
TypeError: can only concatenate str (not "NoneType") to str
2024-11-06 02:37:49,328 - INFO - 36.226.71.243 - - [06/Nov/2024 02:37:49] "[35m[1mGET /get_treatment?form_id=5606&protocolid1098&patientid=9377 HTTP/1.1[0m" 500 -
2024-11-06 02:38:28,925 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 70, in get_treatment
    logging.error("protocolid:"+protocolid)
TypeError: can only concatenate str (not "NoneType") to str
2024-11-06 02:38:28,927 - INFO - 36.226.71.243 - - [06/Nov/2024 02:38:28] "[35m[1mGET /get_treatment?form_id=5606&protocolid1098&patientid=9377 HTTP/1.1[0m" 500 -
2024-11-06 02:40:06,699 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-06 02:40:06,699 - INFO - [33mPress CTRL+C to quit[0m
2024-11-06 02:44:22,319 - ERROR - formid:5606
2024-11-06 02:44:22,320 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 73, in get_treatment
    logging.error("protocolid:"+protocolid)
TypeError: can only concatenate str (not "NoneType") to str
2024-11-06 02:44:22,323 - INFO - 36.226.71.243 - - [06/Nov/2024 02:44:22] "[35m[1mGET /get_treatment?formid=5606&protocolid1098&patientid=9377 HTTP/1.1[0m" 500 -
2024-11-06 02:47:22,785 - ERROR - formid:5606
2024-11-06 02:47:22,785 - ERROR - protocolid:1098
2024-11-06 02:47:22,785 - ERROR - patientid:9377
2024-11-06 02:47:24,249 - ERROR - dcis:2
2024-11-06 02:47:24,249 - ERROR - pathology:2
2024-11-06 02:47:27,684 - INFO - 36.226.71.243 - - [06/Nov/2024 02:47:27] "GET /get_treatment?formid=5606&protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-06 02:54:06,806 - ERROR - formid:5606
2024-11-06 02:54:06,806 - ERROR - protocolid:1098
2024-11-06 02:54:06,806 - ERROR - patientid:9377
2024-11-06 02:54:06,913 - ERROR - dcis:2
2024-11-06 02:54:06,913 - ERROR - pathology:2
2024-11-06 02:54:10,208 - INFO - 36.226.71.243 - - [06/Nov/2024 02:54:10] "GET /get_treatment?formid=5606&protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-06 03:04:23,907 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-06 03:04:23,912 - INFO - [33mPress CTRL+C to quit[0m
2024-11-06 03:04:42,774 - ERROR - formid:5606
2024-11-06 03:04:42,775 - ERROR - protocolid:1098
2024-11-06 03:04:42,775 - ERROR - patientid:9377
2024-11-06 03:04:44,310 - ERROR - random_arm:RT
2024-11-06 03:04:44,310 - ERROR - dcis:2
2024-11-06 03:04:44,310 - ERROR - pathology:2
2024-11-06 03:04:44,311 - INFO - 36.226.71.243 - - [06/Nov/2024 03:04:44] "GET /get_treatment?formid=5606&protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-06 03:32:59,072 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-06 03:32:59,077 - INFO - [33mPress CTRL+C to quit[0m
2024-11-06 03:34:52,819 - ERROR - formid:5606
2024-11-06 03:34:52,819 - ERROR - protocolid:1098
2024-11-06 03:34:52,819 - ERROR - patientid:9377
2024-11-06 03:34:54,414 - ERROR - random_arm:RT
2024-11-06 03:34:54,414 - ERROR - dcis:2
2024-11-06 03:34:54,414 - ERROR - pathology:2
2024-11-06 03:34:54,415 - INFO - 36.226.71.243 - - [06/Nov/2024 03:34:54] "GET /get_treatment?formid=5606&protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-06 03:35:38,585 - ERROR - formid:5606
2024-11-06 03:35:38,585 - ERROR - protocolid:1098
2024-11-06 03:35:38,585 - ERROR - patientid:9377
2024-11-06 03:35:38,728 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 82, in get_treatment
    logging.error("random_arm:"+random_arm)
TypeError: can only concatenate str (not "NoneType") to str
2024-11-06 03:35:38,731 - INFO - 36.226.71.243 - - [06/Nov/2024 03:35:38] "[35m[1mGET /get_treatment?formid=5606&protocolid=1098&patientid=9377 HTTP/1.1[0m" 500 -
2024-11-06 03:37:49,887 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-06 03:37:49,887 - INFO - [33mPress CTRL+C to quit[0m
2024-11-06 03:40:45,618 - ERROR - formid:5606
2024-11-06 03:40:45,619 - ERROR - protocolid:1098
2024-11-06 03:40:45,619 - ERROR - patientid:9377
2024-11-06 03:40:47,123 - ERROR - dcis:2
2024-11-06 03:40:47,123 - ERROR - pathology:2
2024-11-06 03:40:48,116 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 104, in get_treatment
    with open("config.yml", "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yml'
2024-11-06 03:40:48,118 - INFO - 36.226.71.243 - - [06/Nov/2024 03:40:48] "[35m[1mGET /get_treatment?formid=5606&protocolid=1098&patientid=9377 HTTP/1.1[0m" 500 -
2024-11-06 03:42:22,678 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-06 03:42:22,678 - INFO - [33mPress CTRL+C to quit[0m
2024-11-06 03:42:31,441 - ERROR - formid:5606
2024-11-06 03:42:31,441 - ERROR - protocolid:1098
2024-11-06 03:42:31,441 - ERROR - patientid:9377
2024-11-06 03:42:32,936 - ERROR - dcis:2
2024-11-06 03:42:32,936 - ERROR - pathology:2
2024-11-06 03:42:32,937 - INFO - 36.226.71.243 - - [06/Nov/2024 03:42:32] "GET /get_treatment?formid=5606&protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-06 03:43:15,661 - ERROR - formid:5606
2024-11-06 03:43:15,661 - ERROR - protocolid:1098
2024-11-06 03:43:15,661 - ERROR - patientid:9377
2024-11-06 03:43:15,805 - ERROR - dcis:2
2024-11-06 03:43:15,805 - ERROR - pathology:2
2024-11-06 03:43:16,855 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 122, in get_treatment
    to_address=to_address,
NameError: name 'to_address' is not defined
2024-11-06 03:43:16,858 - INFO - 36.226.71.243 - - [06/Nov/2024 03:43:16] "[35m[1mGET /get_treatment?formid=5606&protocolid=1098&patientid=9377 HTTP/1.1[0m" 500 -
2024-11-06 03:53:33,777 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-06 03:53:33,777 - INFO - [33mPress CTRL+C to quit[0m
2024-11-06 03:53:46,933 - ERROR - formid:5606
2024-11-06 03:53:46,933 - ERROR - protocolid:1098
2024-11-06 03:53:46,933 - ERROR - patientid:9377
2024-11-06 03:53:48,467 - ERROR - dcis:2
2024-11-06 03:53:48,468 - ERROR - pathology:2
2024-11-06 03:53:52,284 - INFO - 36.226.71.243 - - [06/Nov/2024 03:53:52] "GET /get_treatment?formid=5606&protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-06 03:58:30,432 - ERROR - formid:5606
2024-11-06 03:58:30,432 - ERROR - protocolid:1098
2024-11-06 03:58:30,432 - ERROR - patientid:9377
2024-11-06 03:58:30,590 - ERROR - dcis:2
2024-11-06 03:58:30,590 - ERROR - pathology:2
2024-11-06 03:58:33,769 - INFO - 36.226.71.243 - - [06/Nov/2024 03:58:33] "GET /get_treatment?formid=5606&protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-06 04:00:22,792 - ERROR - formid:5606
2024-11-06 04:00:22,792 - ERROR - protocolid:1098
2024-11-06 04:00:22,793 - ERROR - patientid:9377
2024-11-06 04:00:22,945 - ERROR - dcis:2
2024-11-06 04:00:22,945 - ERROR - pathology:2
2024-11-06 04:00:22,946 - INFO - 36.226.71.243 - - [06/Nov/2024 04:00:22] "GET /get_treatment?formid=5606&protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-06 04:23:29,267 - ERROR - 154.213.185.206 - - [06/Nov/2024 04:23:29] code 400, message Bad request syntax ('JDWP-Handshake')
2024-11-06 04:23:29,268 - INFO - 154.213.185.206 - - [06/Nov/2024 04:23:29] "[35m[1mJDWP-Handshake[0m" HTTPStatus.BAD_REQUEST -
2024-11-06 08:02:19,311 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-06 08:02:19,312 - INFO - [33mPress CTRL+C to quit[0m
2024-11-06 08:02:44,524 - INFO - 120.126.47.13 - - [06/Nov/2024 08:02:44] "GET /confirm HTTP/1.1" 200 -
2024-11-06 08:02:55,199 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 100, in get_treatment
    logging.error("formid:"+formid)
TypeError: can only concatenate str (not "NoneType") to str
2024-11-06 08:02:55,202 - INFO - 120.126.47.13 - - [06/Nov/2024 08:02:55] "[35m[1mGET /get_treatment HTTP/1.1[0m" 500 -
2024-11-06 08:07:13,172 - ERROR - formid:5606
2024-11-06 08:07:13,172 - ERROR - protocolid:1098
2024-11-06 08:07:13,172 - ERROR - patientid:9377
2024-11-06 08:07:14,694 - ERROR - dcis:2
2024-11-06 08:07:14,694 - ERROR - pathology:2
2024-11-06 08:07:14,695 - INFO - 36.226.71.243 - - [06/Nov/2024 08:07:14] "GET /get_treatment?formid=5606&protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-06 08:09:57,138 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-06 08:09:57,138 - INFO - [33mPress CTRL+C to quit[0m
2024-11-06 08:10:09,140 - INFO - 120.126.47.13 - - [06/Nov/2024 08:10:09] "GET /confirm HTTP/1.1" 200 -
2024-11-06 08:10:13,959 - ERROR - formid:null
2024-11-06 08:10:13,959 - ERROR - protocolid:null
2024-11-06 08:10:13,959 - ERROR - patientid:null
2024-11-06 08:10:15,333 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 105, in get_treatment
    dcis = get_value(protocolid, patientid, 55926)
  File "/app/csis_data.py", line 36, in get_value
    cursor.execute(query, patientid=patientid, protocolid=protocolid, datapointid=datapointid)
cx_Oracle.DatabaseError: ORA-01722: invalid number
2024-11-06 08:10:15,335 - INFO - 120.126.47.13 - - [06/Nov/2024 08:10:15] "[35m[1mGET /get_treatment?formid=null&protocolid=null&patientid=null HTTP/1.1[0m" 500 -
2024-11-06 08:10:30,981 - ERROR - formid:null
2024-11-06 08:10:30,981 - ERROR - protocolid:null
2024-11-06 08:10:30,981 - ERROR - patientid:null
2024-11-06 08:10:31,035 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 105, in get_treatment
    dcis = get_value(protocolid, patientid, 55926)
  File "/app/csis_data.py", line 36, in get_value
    cursor.execute(query, patientid=patientid, protocolid=protocolid, datapointid=datapointid)
cx_Oracle.DatabaseError: ORA-01722: invalid number
2024-11-06 08:10:31,036 - INFO - 120.126.47.13 - - [06/Nov/2024 08:10:31] "[35m[1mGET /get_treatment?formid=null&protocolid=null&patientid=null HTTP/1.1[0m" 500 -
2024-11-06 08:10:59,280 - ERROR - formid:null
2024-11-06 08:10:59,280 - ERROR - protocolid:null
2024-11-06 08:10:59,280 - ERROR - patientid:null
2024-11-06 08:10:59,332 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 105, in get_treatment
    dcis = get_value(protocolid, patientid, 55926)
  File "/app/csis_data.py", line 36, in get_value
    cursor.execute(query, patientid=patientid, protocolid=protocolid, datapointid=datapointid)
cx_Oracle.DatabaseError: ORA-01722: invalid number
2024-11-06 08:10:59,334 - INFO - 120.126.47.13 - - [06/Nov/2024 08:10:59] "[35m[1mGET /get_treatment?formid=null&protocolid=null&patientid=null HTTP/1.1[0m" 500 -
2024-11-06 08:11:04,613 - ERROR - formid:null
2024-11-06 08:11:04,613 - ERROR - protocolid:null
2024-11-06 08:11:04,613 - ERROR - patientid:null
2024-11-06 08:11:04,665 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 105, in get_treatment
    dcis = get_value(protocolid, patientid, 55926)
  File "/app/csis_data.py", line 36, in get_value
    cursor.execute(query, patientid=patientid, protocolid=protocolid, datapointid=datapointid)
cx_Oracle.DatabaseError: ORA-01722: invalid number
2024-11-06 08:11:04,667 - INFO - 120.126.47.13 - - [06/Nov/2024 08:11:04] "[35m[1mGET /get_treatment?formid=null&protocolid=null&patientid=null HTTP/1.1[0m" 500 -
2024-11-06 08:11:56,115 - INFO - 120.126.47.13 - - [06/Nov/2024 08:11:56] "GET /confirm?formid=5606&protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-06 08:12:05,976 - ERROR - formid:5606
2024-11-06 08:12:05,977 - ERROR - protocolid:1098
2024-11-06 08:12:05,977 - ERROR - patientid:9377
2024-11-06 08:12:06,136 - ERROR - dcis:2
2024-11-06 08:12:06,137 - ERROR - pathology:2
2024-11-06 08:12:06,137 - INFO - 120.126.47.13 - - [06/Nov/2024 08:12:06] "GET /get_treatment?formid=5606&protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-06 09:00:35,866 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-06 09:00:35,866 - INFO - [33mPress CTRL+C to quit[0m
2024-11-06 09:07:38,055 - ERROR - Exception on /confirm [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 33, in confirm_page
    mrn = get_mrn(patientid)
NameError: name 'get_mrn' is not defined
2024-11-06 09:07:38,057 - INFO - 120.126.47.13 - - [06/Nov/2024 09:07:38] "[35m[1mGET /confirm?formid=5606&protocolid=1098&patientid=9377 HTTP/1.1[0m" 500 -
2024-11-06 09:07:55,676 - ERROR - Exception on /confirm [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 33, in confirm_page
    mrn = get_mrn(patientid)
NameError: name 'get_mrn' is not defined
2024-11-06 09:07:55,677 - INFO - 120.126.47.13 - - [06/Nov/2024 09:07:55] "[35m[1mGET /confirm?formid=5606&protocolid=1098&patientid=9377 HTTP/1.1[0m" 500 -
2024-11-06 09:11:11,045 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-06 09:11:11,045 - INFO - [33mPress CTRL+C to quit[0m
2024-11-06 09:11:22,998 - INFO - 120.126.47.13 - - [06/Nov/2024 09:11:22] "GET /confirm?formid=5606&protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-06 09:18:59,915 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-06 09:18:59,925 - INFO - [33mPress CTRL+C to quit[0m
2024-11-06 09:19:04,120 - ERROR - Exception on /confirm [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 37, in confirm_page
    if dcis_value == 1:
NameError: name 'dcis_value' is not defined
2024-11-06 09:19:04,123 - INFO - 120.126.47.13 - - [06/Nov/2024 09:19:04] "[35m[1mGET /confirm?formid=5606&protocolid=1098&patientid=9377 HTTP/1.1[0m" 500 -
2024-11-06 09:20:46,634 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-06 09:20:46,636 - INFO - [33mPress CTRL+C to quit[0m
2024-11-06 09:20:49,389 - INFO - 120.126.47.13 - - [06/Nov/2024 09:20:49] "GET /confirm?formid=5606&protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-06 09:22:38,806 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-06 09:22:38,806 - INFO - [33mPress CTRL+C to quit[0m
2024-11-06 09:22:56,311 - ERROR - Exception on /confirm [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 36, in confirm_page
    logginig.error(dcis_value)
NameError: name 'logginig' is not defined
2024-11-06 09:22:56,314 - INFO - 120.126.47.13 - - [06/Nov/2024 09:22:56] "[35m[1mGET /confirm?formid=5606&protocolid=1098&patientid=9377 HTTP/1.1[0m" 500 -
2024-11-07 01:02:57,104 - INFO - 198.235.24.184 - - [07/Nov/2024 01:02:57] "GET / HTTP/1.1" 200 -
2024-11-07 01:23:13,870 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 01:23:13,870 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 01:23:30,040 - ERROR - Exception on /confirm [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 36, in confirm_page
    logginig.error(dcis_value)
NameError: name 'logginig' is not defined
2024-11-07 01:23:30,042 - INFO - 120.126.47.13 - - [07/Nov/2024 01:23:30] "[35m[1mGET /confirm?formid=5606&protocolid=1098&patientid=9377 HTTP/1.1[0m" 500 -
2024-11-07 01:25:22,420 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 01:25:22,420 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 01:25:31,914 - ERROR - 2
2024-11-07 01:25:31,928 - INFO - 120.126.47.13 - - [07/Nov/2024 01:25:31] "GET /confirm?formid=5606&protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 01:30:15,565 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 01:30:15,569 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 01:30:23,826 - ERROR - 2
2024-11-07 01:30:23,838 - INFO - 120.126.47.13 - - [07/Nov/2024 01:30:23] "GET /confirm?formid=5606&protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 01:40:16,406 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 01:40:16,406 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 01:42:22,257 - ERROR - 2
2024-11-07 01:42:22,266 - INFO - 120.126.47.13 - - [07/Nov/2024 01:42:22] "GET /confirm?formid=5606&protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 01:43:11,919 - ERROR - formid:
2024-11-07 01:43:11,920 - ERROR - protocolid:
2024-11-07 01:43:11,920 - ERROR - patientid:
2024-11-07 01:43:12,086 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 141, in get_treatment
    logging.error("dcis:"+dcis)
TypeError: can only concatenate str (not "NoneType") to str
2024-11-07 01:43:12,089 - INFO - 120.126.47.13 - - [07/Nov/2024 01:43:12] "[35m[1mGET /get_treatment?formid=&protocolid=&patientid= HTTP/1.1[0m" 500 -
2024-11-07 01:43:12,392 - ERROR - formid:
2024-11-07 01:43:12,392 - ERROR - protocolid:
2024-11-07 01:43:12,392 - ERROR - patientid:
2024-11-07 01:43:12,535 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 141, in get_treatment
    logging.error("dcis:"+dcis)
TypeError: can only concatenate str (not "NoneType") to str
2024-11-07 01:43:12,536 - INFO - 120.126.47.13 - - [07/Nov/2024 01:43:12] "[35m[1mGET /get_treatment?formid=&protocolid=&patientid= HTTP/1.1[0m" 500 -
2024-11-07 01:43:23,902 - ERROR - formid:
2024-11-07 01:43:23,902 - ERROR - protocolid:
2024-11-07 01:43:23,903 - ERROR - patientid:
2024-11-07 01:43:24,052 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 141, in get_treatment
    logging.error("dcis:"+dcis)
TypeError: can only concatenate str (not "NoneType") to str
2024-11-07 01:43:24,054 - INFO - 120.126.47.13 - - [07/Nov/2024 01:43:24] "[35m[1mGET /get_treatment?formid=&protocolid=&patientid= HTTP/1.1[0m" 500 -
2024-11-07 01:48:07,911 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 01:48:07,911 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 01:51:43,808 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 01:51:43,810 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 01:52:14,344 - ERROR - 2
2024-11-07 01:52:14,354 - INFO - 120.126.47.13 - - [07/Nov/2024 01:52:14] "GET /confirm?formid=5606&protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 01:52:26,475 - INFO - 120.126.47.13 - - [07/Nov/2024 01:52:26] "GET /get_treatment?formid=&protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 01:53:25,699 - ERROR - 2
2024-11-07 01:53:25,700 - INFO - 120.126.47.13 - - [07/Nov/2024 01:53:25] "GET /confirm?formid=5606&protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 01:53:36,510 - INFO - 120.126.47.13 - - [07/Nov/2024 01:53:36] "GET /get_treatment?formid=&protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 02:06:10,552 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 02:06:10,553 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 02:06:28,984 - ERROR - 2
2024-11-07 02:06:28,994 - INFO - 120.126.47.13 - - [07/Nov/2024 02:06:28] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 02:06:40,440 - INFO - 120.126.47.13 - - [07/Nov/2024 02:06:40] "GET /get_treatment?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 02:14:02,630 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 02:14:02,630 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 02:14:16,766 - ERROR - 2
2024-11-07 02:14:16,776 - INFO - 120.126.47.13 - - [07/Nov/2024 02:14:16] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 02:14:22,591 - INFO - 120.126.47.13 - - [07/Nov/2024 02:14:22] "GET /get_treatment?protocolid=1098&patientid=9377&mrn=0425-003&dcis_display=DCIS%20size:%20&gt;%2010%20mm&pathology_display=Pathology%20margins:%20≥%2010%20mm HTTP/1.1" 200 -
2024-11-07 02:22:46,001 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 02:22:46,005 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 02:23:04,427 - INFO - 120.126.47.13 - - [07/Nov/2024 02:23:04] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 02:23:06,672 - ERROR - DCIS size: 
2024-11-07 02:23:06,672 - ERROR - [CSIS Randomization] 0425-003
2024-11-07 02:23:06,673 - ERROR - Series No. of Allocation: 
Patient Study ID: 0425-003
Randomized Treatment Arm: Tamoxifen
Stratum:
DCIS size: 
Pathology margins: ≥ 10 mm

2024-11-07 02:23:06,673 - INFO - 120.126.47.13 - - [07/Nov/2024 02:23:06] "GET /get_treatment?protocolid=1098&patientid=9377&mrn=0425-003&dcis_display=DCIS%20size:%20&gt;%2010%20mm&pathology_display=Pathology%20margins:%20≥%2010%20mm HTTP/1.1" 200 -
2024-11-07 02:27:31,052 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 02:27:31,053 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 02:28:08,543 - INFO - 120.126.47.13 - - [07/Nov/2024 02:28:08] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 02:28:11,576 - ERROR - DCIS size: 10 mm
2024-11-07 02:28:11,576 - ERROR - [CSIS Randomization] 0425-003
2024-11-07 02:28:11,576 - ERROR - Series No. of Allocation: 
Patient Study ID: 0425-003
Randomized Treatment Arm: RT
Stratum:
DCIS size: 10 mm
Pathology margins: ≥ 10 mm

2024-11-07 02:28:11,577 - INFO - 120.126.47.13 - - [07/Nov/2024 02:28:11] "GET /get_treatment?protocolid=1098&patientid=9377&mrn=0425-003&dcis_display=DCIS%20size:%2010%20mm&pathology_display=Pathology%20margins:%20≥%2010%20mm HTTP/1.1" 200 -
2024-11-07 02:39:35,771 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 02:39:35,771 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 02:39:45,713 - INFO - 120.126.47.13 - - [07/Nov/2024 02:39:45] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 02:39:47,530 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 143, in get_treatment
    params = json.loads(data)
NameError: name 'json' is not defined
2024-11-07 02:39:47,532 - INFO - 120.126.47.13 - - [07/Nov/2024 02:39:47] "[35m[1mGET /get_treatment?data={"prid":"1098","ptientid":"9377","dcis":"DCIS%20size:%2010%20mm","path":"Pathology%20margins:%20≥%2010%20mm"} HTTP/1.1[0m" 500 -
2024-11-07 02:42:44,859 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 02:42:44,859 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 02:42:47,494 - INFO - 120.126.47.13 - - [07/Nov/2024 02:42:47] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 02:42:48,487 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 155, in get_treatment
    treatment = get_number(dcis, pathology)
  File "app.py", line 93, in get_number
    sheet_name = get_sheet_name(paraA, paraB)
  File "app.py", line 89, in get_sheet_name
    raise ValueError("Invalid values for paraA and paraB")
ValueError: Invalid values for paraA and paraB
2024-11-07 02:42:48,489 - INFO - 120.126.47.13 - - [07/Nov/2024 02:42:48] "[35m[1mGET /get_treatment?data={"prid":"1098","ptientid":"9377","dcis":"DCIS%20size:%2010%20mm","path":"Pathology%20margins:%20≥%2010%20mm"} HTTP/1.1[0m" 500 -
2024-11-07 02:47:28,836 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 02:47:28,840 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 02:47:39,865 - INFO - 120.126.47.13 - - [07/Nov/2024 02:47:39] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 02:47:44,207 - ERROR - DCIS size: 10 mm
2024-11-07 02:47:44,207 - ERROR - [CSIS Randomization] None
2024-11-07 02:47:44,208 - ERROR - Series No. of Allocation: 
Patient Study ID: None
Randomized Treatment Arm: RT
Stratum:
DCIS size: 10 mm
Pathology margins: ≥ 10 mm

2024-11-07 02:47:44,208 - INFO - 120.126.47.13 - - [07/Nov/2024 02:47:44] "GET /get_treatment?data={"prid":"1098","ptid":"9377","dcis":"DCIS%20size:%2010%20mm","path":"Pathology%20margins:%20≥%2010%20mm"} HTTP/1.1" 200 -
2024-11-07 02:48:18,989 - INFO - 120.126.47.13 - - [07/Nov/2024 02:48:18] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 02:48:53,495 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 02:48:53,496 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 02:48:57,809 - INFO - 120.126.47.13 - - [07/Nov/2024 02:48:57] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 02:49:01,947 - ERROR - DCIS size: &gt; 10 mm
2024-11-07 02:49:01,947 - ERROR - [CSIS Randomization] None
2024-11-07 02:49:01,947 - ERROR - Series No. of Allocation: 
Patient Study ID: None
Randomized Treatment Arm: RT
Stratum:
DCIS size: &gt; 10 mm
Pathology margins: ≥ 10 mm

2024-11-07 02:49:01,948 - INFO - 120.126.47.13 - - [07/Nov/2024 02:49:01] "GET /get_treatment?data={"prid":"1098","ptid":"9377","dcis":"DCIS%20size:%20%26gt;%2010%20mm","path":"Pathology%20margins:%20≥%2010%20mm"} HTTP/1.1" 200 -
2024-11-07 02:52:50,996 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 02:52:51,010 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 02:53:38,329 - INFO - 120.126.47.13 - - [07/Nov/2024 02:53:38] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 02:54:26,131 - INFO - 120.126.47.13 - - [07/Nov/2024 02:54:26] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 02:55:48,186 - INFO - 120.126.47.13 - - [07/Nov/2024 02:55:48] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 02:59:16,557 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 02:59:16,557 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 03:03:33,452 - INFO - 120.126.47.13 - - [07/Nov/2024 03:03:33] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 03:03:50,578 - ERROR - &#34;DCIS size: &gt; 10 mm&#34;
2024-11-07 03:03:50,578 - ERROR - [CSIS Randomization] None
2024-11-07 03:03:50,578 - ERROR - Series No. of Allocation: 
Patient Study ID: None
Randomized Treatment Arm: Tamoxifen
Stratum:
&#34;DCIS size: &gt; 10 mm&#34;
Pathology margins: ≥ 10 mm

2024-11-07 03:03:53,212 - INFO - 120.126.47.13 - - [07/Nov/2024 03:03:53] "GET /get_treatment?data={"prid":"1098","ptid":"9377","dcis":"%26%2334;DCIS%20size:%20%26gt;%2010%20mm%26%2334;","path":"Pathology%20margins:%20≥%2010%20mm"} HTTP/1.1" 200 -
2024-11-07 03:08:09,576 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 03:08:09,579 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 03:10:13,462 - INFO - 120.126.47.13 - - [07/Nov/2024 03:10:13] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 03:10:22,858 - INFO - 120.126.47.13 - - [07/Nov/2024 03:10:22] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 03:20:50,426 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 142, in get_treatment
    params = json.loads(data)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 37 (char 36)
2024-11-07 03:20:50,429 - INFO - 120.126.47.13 - - [07/Nov/2024 03:20:50] "[35m[1mGET /get_treatment?data={"prid":"1098","ptid":"9377","dcis":"DCIS%20size:%20&gt;%2010%20mm","path":"Pathology%20margins:%20≥%2010%20mm"} HTTP/1.1[0m" 500 -
2024-11-07 03:26:10,878 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 03:26:10,879 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 03:26:34,576 - INFO - 120.126.47.13 - - [07/Nov/2024 03:26:34] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 03:30:38,766 - ERROR - DCIS size: &gt; 10 mm
2024-11-07 03:30:38,766 - ERROR - [CSIS Randomization] None
2024-11-07 03:30:38,767 - ERROR - Series No. of Allocation: 
Patient Study ID: None
Randomized Treatment Arm: Tamoxifen
Stratum:
DCIS size: &gt; 10 mm
Pathology margins: ≥ 10 mm

2024-11-07 03:30:42,112 - INFO - 120.126.47.13 - - [07/Nov/2024 03:30:42] "GET /get_treatment?data={"prid":"1098","ptid":"9377","dcis":"DCIS%20size:%20%26gt;%2010%20mm","path":"Pathology%20margins:%20≥%2010%20mm"} HTTP/1.1" 200 -
2024-11-07 03:34:41,854 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 03:34:41,854 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 03:34:48,048 - INFO - 120.126.47.13 - - [07/Nov/2024 03:34:48] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 03:34:58,537 - ERROR - DCIS size: > 10 mm
2024-11-07 03:34:58,537 - ERROR - [CSIS Randomization] None
2024-11-07 03:34:58,537 - ERROR - Series No. of Allocation: 
Patient Study ID: None
Randomized Treatment Arm: Tamoxifen
Stratum:
DCIS size: > 10 mm
Pathology margins: ≥ 10 mm

2024-11-07 03:35:01,010 - INFO - 120.126.47.13 - - [07/Nov/2024 03:35:01] "GET /get_treatment?data={"prid":"1098","ptid":"9377","dcis":"DCIS%20size:%20%26gt;%2010%20mm","path":"Pathology%20margins:%20≥%2010%20mm"} HTTP/1.1" 200 -
2024-11-07 03:45:40,732 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 03:45:40,732 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 03:45:58,474 - INFO - 120.126.47.13 - - [07/Nov/2024 03:45:58] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 03:46:01,142 - INFO - 120.126.47.13 - - [07/Nov/2024 03:46:01] "GET /get_treatment?data={"prid":"1098","ptid":"9377","dcis":"DCIS%20size:%20%26gt;%2010%20mm","path":"Pathology%20margins:%20≥%2010%20mm"} HTTP/1.1" 200 -
2024-11-07 03:46:21,757 - INFO - 120.126.47.13 - - [07/Nov/2024 03:46:21] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 03:46:24,977 - ERROR - DCIS size: > 10 mm
2024-11-07 03:46:24,977 - ERROR - [CSIS Randomization] None
2024-11-07 03:46:24,977 - ERROR - Series No. of Allocation: 29
Patient Study ID: None
Randomized Treatment Arm: Tamoxifen
Stratum:
DCIS size: > 10 mm
Pathology margins: ≥ 10 mm

Cumulative number of patients allocated to the specific treatment arm in each stratum after this randomization:
[{'group1': 0, 'group2': 2, 'group3': 3, 'group4': 24}]

2024-11-07 03:46:27,408 - INFO - 120.126.47.13 - - [07/Nov/2024 03:46:27] "GET /get_treatment?data={"prid":"1098","ptid":"9377","dcis":"DCIS%20size:%20%26gt;%2010%20mm","path":"Pathology%20margins:%20≥%2010%20mm"} HTTP/1.1" 200 -
2024-11-07 04:17:42,127 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 04:17:42,127 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 04:18:17,423 - INFO - 120.126.47.13 - - [07/Nov/2024 04:18:17] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 04:18:22,682 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 179, in get_treatment
    send_email_based_on_site(treatment, site)
  File "app.py", line 133, in send_email_based_on_site
    result = "\n".join([f"{group_descriptions[key]} : {value}" for key, value in data[0].items()])
AttributeError: 'str' object has no attribute 'items'
2024-11-07 04:18:22,685 - INFO - 120.126.47.13 - - [07/Nov/2024 04:18:22] "[35m[1mGET /get_treatment?data={"prid":"1098","ptid":"9377","dcis":"DCIS%20size:%20%26gt;%2010%20mm","path":"Pathology%20margins:%20≥%2010%20mm","mrn":"0425-003"} HTTP/1.1[0m" 500 -
2024-11-07 04:21:07,850 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 04:21:07,850 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 04:21:18,569 - INFO - 120.126.47.13 - - [07/Nov/2024 04:21:18] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 04:21:20,044 - INFO - 120.126.47.13 - - [07/Nov/2024 04:21:20] "GET /get_treatment?data={"prid":"1098","ptid":"9377","dcis":"DCIS%20size:%20%26gt;%2010%20mm","path":"Pathology%20margins:%20≥%2010%20mm","mrn":"0425-003"} HTTP/1.1" 200 -
2024-11-07 04:21:51,618 - INFO - 120.126.47.13 - - [07/Nov/2024 04:21:51] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 04:21:54,215 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 179, in get_treatment
    send_email_based_on_site(treatment, site)
  File "app.py", line 133, in send_email_based_on_site
    result = "\n".join([f"{group_descriptions[key]} : {value}" for key, value in data[0].items()])
AttributeError: 'str' object has no attribute 'items'
2024-11-07 04:21:54,218 - INFO - 120.126.47.13 - - [07/Nov/2024 04:21:54] "[35m[1mGET /get_treatment?data={"prid":"1098","ptid":"9377","dcis":"DCIS%20size:%20%26gt;%2010%20mm","path":"Pathology%20margins:%20≥%2010%20mm","mrn":"0425-003"} HTTP/1.1[0m" 500 -
2024-11-07 04:25:36,896 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 04:25:36,899 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 04:26:55,501 - INFO - 120.126.47.13 - - [07/Nov/2024 04:26:55] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 04:26:56,395 - INFO - 120.126.47.13 - - [07/Nov/2024 04:26:56] "GET /get_treatment?data={"prid":"1098","ptid":"9377","dcis":"DCIS%20size:%20%26gt;%2010%20mm","path":"Pathology%20margins:%20≥%2010%20mm","mrn":"0425-003"} HTTP/1.1" 200 -
2024-11-07 04:27:27,883 - INFO - 120.126.47.13 - - [07/Nov/2024 04:27:27] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 04:27:32,834 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 179, in get_treatment
    send_email_based_on_site(treatment, site)
  File "app.py", line 133, in send_email_based_on_site
    result = "\n".join([f"{group_descriptions[key]} : {value}" for key, value in data[0].items()])
AttributeError: 'str' object has no attribute 'items'
2024-11-07 04:27:32,836 - INFO - 120.126.47.13 - - [07/Nov/2024 04:27:32] "[35m[1mGET /get_treatment?data={"prid":"1098","ptid":"9377","dcis":"DCIS%20size:%20%26gt;%2010%20mm","path":"Pathology%20margins:%20≥%2010%20mm","mrn":"0425-003"} HTTP/1.1[0m" 500 -
2024-11-07 06:19:29,530 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 06:19:29,530 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 06:20:13,835 - INFO - 120.126.47.13 - - [07/Nov/2024 06:20:13] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 06:20:16,110 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 179, in get_treatment
    send_email_based_on_site(treatment, site)
  File "app.py", line 133, in send_email_based_on_site
    result = "\n".join([f"{group_descriptions[key]} : {value}" for key, value in data[0].items()])
AttributeError: 'str' object has no attribute 'items'
2024-11-07 06:20:16,112 - INFO - 120.126.47.13 - - [07/Nov/2024 06:20:16] "[35m[1mGET /get_treatment?data={"prid":"1098","ptid":"9377","dcis":"DCIS%20size:%20%26gt;%2010%20mm","path":"Pathology%20margins:%20≥%2010%20mm","mrn":"0425-003"} HTTP/1.1[0m" 500 -
2024-11-07 06:22:27,958 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 06:22:27,959 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 06:23:06,049 - INFO - 120.126.47.13 - - [07/Nov/2024 06:23:06] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 06:23:08,540 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 179, in get_treatment
    send_email_based_on_site(treatment, site)
  File "app.py", line 133, in send_email_based_on_site
    result = "\n".join([f"{group_descriptions[key]} : {value}" for key, value in data[0].items()])
AttributeError: 'str' object has no attribute 'items'
2024-11-07 06:23:08,543 - INFO - 120.126.47.13 - - [07/Nov/2024 06:23:08] "[35m[1mGET /get_treatment?data={"prid":"1098","ptid":"9377","dcis":"DCIS%20size:%20%26gt;%2010%20mm","path":"Pathology%20margins:%20≥%2010%20mm","mrn":"0425-003"} HTTP/1.1[0m" 500 -
2024-11-07 06:30:56,801 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 06:30:56,801 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 06:31:13,775 - INFO - 120.126.47.13 - - [07/Nov/2024 06:31:13] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 06:31:16,112 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 179, in get_treatment
    send_email_based_on_site(treatment, site)
  File "app.py", line 133, in send_email_based_on_site
    result = "\n".join([f"{group_descriptions[key]} : {value}" for key, value in data[0].items()])
AttributeError: 'str' object has no attribute 'items'
2024-11-07 06:31:16,114 - INFO - 120.126.47.13 - - [07/Nov/2024 06:31:16] "[35m[1mGET /get_treatment?data={"prid":"1098","ptid":"9377","dcis":"DCIS%20size:%20%26gt;%2010%20mm","path":"Pathology%20margins:%20≥%2010%20mm","mrn":"0425-003"} HTTP/1.1[0m" 500 -
2024-11-07 06:33:48,215 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 06:33:48,219 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 06:34:36,226 - INFO - 120.126.47.13 - - [07/Nov/2024 06:34:36] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 06:34:47,278 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 179, in get_treatment
    send_email_based_on_site(treatment, site)
  File "app.py", line 133, in send_email_based_on_site
    result = "\n".join([f"{group_descriptions[key]} : {value}" for key, value in data[0].items()])
AttributeError: 'str' object has no attribute 'items'
2024-11-07 06:34:47,281 - INFO - 120.126.47.13 - - [07/Nov/2024 06:34:47] "[35m[1mGET /get_treatment?data={"prid":"1098","ptid":"9377","dcis":"DCIS%20size:%20%26gt;%2010%20mm","path":"Pathology%20margins:%20≥%2010%20mm","mrn":"0425-003"} HTTP/1.1[0m" 500 -
2024-11-07 06:38:06,822 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 06:38:06,822 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 06:38:10,903 - INFO - 120.126.47.13 - - [07/Nov/2024 06:38:10] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 06:38:12,936 - ERROR - ===================[{"group1": 0, "group2": 2, "group3": 3, "group4": 4}]
2024-11-07 06:38:12,936 - ERROR - {'group1': 0, 'group2': 2, 'group3': 3, 'group4': 4}
2024-11-07 06:38:13,262 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'group_value'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 179, in get_treatment
    send_email_based_on_site(treatment, site)
  File "app.py", line 137, in send_email_based_on_site
    treatment_counts = calculate_treatment_counts(excel_file)
  File "app.py", line 202, in calculate_treatment_counts
    filtered_df = df[df['group_value'] == expected_value]  # 假設 "column_name" 是包含這些數值的列名稱
  File "/usr/local/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'group_value'
2024-11-07 06:38:13,269 - INFO - 120.126.47.13 - - [07/Nov/2024 06:38:13] "[35m[1mGET /get_treatment?data={"prid":"1098","ptid":"9377","dcis":"DCIS%20size:%20%26gt;%2010%20mm","path":"Pathology%20margins:%20≥%2010%20mm","mrn":"0425-003"} HTTP/1.1[0m" 500 -
2024-11-07 06:39:32,002 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 06:39:32,002 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 06:41:26,152 - INFO - 120.126.47.13 - - [07/Nov/2024 06:41:26] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 06:41:28,536 - ERROR - ===================[{"group1": 0, "group2": 2, "group3": 3, "group4": 4}]
2024-11-07 06:41:28,536 - ERROR - {'group1': 0, 'group2': 2, 'group3': 3, 'group4': 4}
2024-11-07 06:41:30,015 - ERROR - DCIS size: > 10 mm
2024-11-07 06:41:30,015 - ERROR - [CSIS Randomization] 0425-003
2024-11-07 06:41:30,015 - ERROR - Series No. of Allocation: 38
Patient Study ID: 0425-003
Randomized Treatment Arm: Tamoxifen
Stratum:
DCIS size: > 10 mm
Pathology margins: ≥ 10 mm

Expected number of patients: 5000
Up-to-date Results in Randomization:
RT 總計數: 0
Tamoxifen 總計數: 0

Cumulative number of patients allocated to the specific treatment arm in each stratum after this randomization:
Size: ≤ 10 mm & Margin width: 3 to < 10 mm : 0
Size: ≤ 10 mm & Margin width: ≥ 10 mm : 2
Size: > 10 mm & Margin width: 3 to < 10 mm : 3
Size: > 10 mm & Margin width: ≥ 10 mm : 33

2024-11-07 06:41:32,839 - INFO - 120.126.47.13 - - [07/Nov/2024 06:41:32] "GET /get_treatment?data={"prid":"1098","ptid":"9377","dcis":"DCIS%20size:%20%26gt;%2010%20mm","path":"Pathology%20margins:%20≥%2010%20mm","mrn":"0425-003"} HTTP/1.1" 200 -
2024-11-07 06:45:29,828 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 06:45:29,829 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 06:47:56,465 - INFO - 120.126.47.13 - - [07/Nov/2024 06:47:56] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 06:47:59,134 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 179, in get_treatment
    send_email_based_on_site(treatment, site)
  File "app.py", line 137, in send_email_based_on_site
    treatment_counts = calculate_treatment_counts(excel_file)
  File "app.py", line 187, in calculate_treatment_counts
    json_data = json.loads(data)
  File "/usr/local/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
2024-11-07 06:47:59,137 - INFO - 120.126.47.13 - - [07/Nov/2024 06:47:59] "[35m[1mGET /get_treatment?data={"prid":"1098","ptid":"9377","dcis":"DCIS%20size:%20%26gt;%2010%20mm","path":"Pathology%20margins:%20≥%2010%20mm","mrn":"0425-003"} HTTP/1.1[0m" 500 -
2024-11-07 06:49:50,145 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 06:49:50,145 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 06:49:55,764 - INFO - 120.126.47.13 - - [07/Nov/2024 06:49:55] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 06:50:02,042 - INFO - 120.126.47.13 - - [07/Nov/2024 06:50:02] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 06:50:05,634 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 179, in get_treatment
    send_email_based_on_site(treatment, site)
  File "app.py", line 137, in send_email_based_on_site
    treatment_counts = calculate_treatment_counts(excel_file)
  File "app.py", line 187, in calculate_treatment_counts
    group_data = data[0]
KeyError: 0
2024-11-07 06:50:05,636 - INFO - 120.126.47.13 - - [07/Nov/2024 06:50:05] "[35m[1mGET /get_treatment?data={"prid":"1098","ptid":"9377","dcis":"DCIS%20size:%20%26gt;%2010%20mm","path":"Pathology%20margins:%20≥%2010%20mm","mrn":"0425-003"} HTTP/1.1[0m" 500 -
2024-11-07 06:55:09,153 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 06:55:09,153 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 06:55:12,030 - INFO - 120.126.47.13 - - [07/Nov/2024 06:55:12] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 06:55:19,752 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 179, in get_treatment
    send_email_based_on_site(treatment, site)
  File "app.py", line 137, in send_email_based_on_site
    treatment_counts = calculate_treatment_counts(excel_file)
  File "app.py", line 187, in calculate_treatment_counts
    group_data = data[0]
KeyError: 0
2024-11-07 06:55:19,754 - INFO - 120.126.47.13 - - [07/Nov/2024 06:55:19] "[35m[1mGET /get_treatment?data={"prid":"1098","ptid":"9377","dcis":"DCIS%20size:%20%26gt;%2010%20mm","path":"Pathology%20margins:%20≥%2010%20mm","mrn":"0425-003"} HTTP/1.1[0m" 500 -
2024-11-07 06:57:00,648 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 06:57:00,651 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 06:57:03,746 - INFO - 120.126.47.13 - - [07/Nov/2024 06:57:03] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 06:57:05,359 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 179, in get_treatment
    send_email_based_on_site(treatment, site)
  File "app.py", line 137, in send_email_based_on_site
    treatment_counts = calculate_treatment_counts(excel_file)
  File "app.py", line 189, in calculate_treatment_counts
    logging.error("========="+data)
TypeError: can only concatenate str (not "dict") to str
2024-11-07 06:57:05,361 - INFO - 120.126.47.13 - - [07/Nov/2024 06:57:05] "[35m[1mGET /get_treatment?data={"prid":"1098","ptid":"9377","dcis":"DCIS%20size:%20%26gt;%2010%20mm","path":"Pathology%20margins:%20≥%2010%20mm","mrn":"0425-003"} HTTP/1.1[0m" 500 -
2024-11-07 06:57:52,038 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 06:57:52,038 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 06:58:11,601 - INFO - 120.126.47.13 - - [07/Nov/2024 06:58:11] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 06:58:19,352 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'group_value'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 179, in get_treatment
    send_email_based_on_site(treatment, site)
  File "app.py", line 137, in send_email_based_on_site
    treatment_counts = calculate_treatment_counts(excel_file)
  File "app.py", line 199, in calculate_treatment_counts
    filtered_df = df[df['group_value'] == expected_value]  # 假設 "column_name" 是包含這些數值的列名稱
  File "/usr/local/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'group_value'
2024-11-07 06:58:19,361 - INFO - 120.126.47.13 - - [07/Nov/2024 06:58:19] "[35m[1mGET /get_treatment?data={"prid":"1098","ptid":"9377","dcis":"DCIS%20size:%20%26gt;%2010%20mm","path":"Pathology%20margins:%20≥%2010%20mm","mrn":"0425-003"} HTTP/1.1[0m" 500 -
2024-11-07 07:05:01,077 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 07:05:01,078 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 07:07:53,292 - INFO - 120.126.47.13 - - [07/Nov/2024 07:07:53] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 07:07:55,578 - ERROR - Exception on /get_treatment [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 179, in get_treatment
    send_email_based_on_site(treatment, site)
  File "app.py", line 137, in send_email_based_on_site
    treatment_counts = calculate_treatment_counts(excel_file)
  File "app.py", line 186, in calculate_treatment_counts
    group_data = data[0]  # 取得第一個字典，包含 group1, group2 等資料
KeyError: 0
2024-11-07 07:07:55,581 - INFO - 120.126.47.13 - - [07/Nov/2024 07:07:55] "[35m[1mGET /get_treatment?data={"prid":"1098","ptid":"9377","dcis":"DCIS%20size:%20%26gt;%2010%20mm","path":"Pathology%20margins:%20≥%2010%20mm","mrn":"0425-003"} HTTP/1.1[0m" 500 -
2024-11-07 07:12:57,429 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.0.2:5000
2024-11-07 07:12:57,429 - INFO - [33mPress CTRL+C to quit[0m
2024-11-07 07:13:01,220 - INFO - 120.126.47.13 - - [07/Nov/2024 07:13:01] "GET /confirm?protocolid=1098&patientid=9377 HTTP/1.1" 200 -
2024-11-07 07:13:04,785 - ERROR - DCIS size: > 10 mm
2024-11-07 07:13:04,785 - ERROR - [CSIS Randomization] DCIS_step2_Random 0425-003
2024-11-07 07:13:04,785 - ERROR - Randomized Treatment Allocation:

Series No. of Allocation: 45
Patient Study ID: 0425-003
Randomized Treatment Arm: RT
Stratum:
DCIS size: > 10 mm
Pathology margins: ≥ 10 mm

Expected number of patients: 5000
Up-to-date Results in Randomization:
RT: 18
Tamoxifen: 27

Cumulative number of patients allocated to the specific treatment arm in each stratum after this randomization:
Size: ≤ 10 mm & Margin width: 3 to < 10 mm : 0
Size: ≤ 10 mm & Margin width: ≥ 10 mm : 2
Size: > 10 mm & Margin width: 3 to < 10 mm : 3
Size: > 10 mm & Margin width: ≥ 10 mm : 40

2024-11-07 07:13:08,237 - INFO - 120.126.47.13 - - [07/Nov/2024 07:13:08] "GET /get_treatment?data={"prid":"1098","ptid":"9377","dcis":"DCIS%20size:%20%26gt;%2010%20mm","path":"Pathology%20margins:%20≥%2010%20mm","mrn":"0425-003"} HTTP/1.1" 200 -
2024-11-07 07:18:53,051 - ERROR - DCIS size: > 10 mm
2024-11-07 07:18:53,051 - ERROR - [CSIS Randomization] DCIS_step2_Random 0425-003
2024-11-07 07:18:53,051 - ERROR - Randomized Treatment Allocation:

Series No. of Allocation: 46
Patient Study ID: 0425-003
Randomized Treatment Arm: RT
Stratum:
DCIS size: > 10 mm
Pathology margins: ≥ 10 mm

Expected number of patients: 5000
Up-to-date Results in Randomization:
RT: 19
Tamoxifen: 27

Cumulative number of patients allocated to the specific treatment arm in each stratum after this randomization:
Size: ≤ 10 mm & Margin width: 3 to < 10 mm : 0
Size: ≤ 10 mm & Margin width: ≥ 10 mm : 2
Size: > 10 mm & Margin width: 3 to < 10 mm : 3
Size: > 10 mm & Margin width: ≥ 10 mm : 41

2024-11-07 07:18:55,447 - INFO - 120.126.47.13 - - [07/Nov/2024 07:18:55] "GET /get_treatment?data={"prid":"1098","ptid":"9377","dcis":"DCIS%20size:%20%26gt;%2010%20mm","path":"Pathology%20margins:%20≥%2010%20mm","mrn":"0425-003"} HTTP/1.1" 200 -
